logging:
   level: INFO
   
   loggers:
      "com.github.jonevn.properties.server": DEBUG
   
   appenders:
      - type: console
        threshold: DEBUG
        target: stdout
        
      - type: file
        currentLogFilename: ./logs/property-server.log
        archivedLogFilenamePattern: ./logs/archive/property-server-%d.log.gz
        archivedFileCount: 10
        timeZone: UTC
   

git:
   repositoryUrl: file:///mnt/nas/repos/properties.git
   branch: master
   pathToCloneTo: .

properties:
   excludedFilePatterns: 
      - .*/other.properties
      - .*/exclude/.*
      
